import csv
import difflib
import os
import re
import sqlite3
import xml.etree.ElementTree as ET
import zipfile
from datetime import date, datetime, timedelta
from pathlib import Path

from flask import current_app, g
import psycopg
from psycopg.rows import dict_row
from werkzeug.security import generate_password_hash


WORKBOOK_BANK_SHEET = "Bank"
WORKBOOK_CANDIDATES = (
    "Accounts 2025-26.xlsx",
    "LodgeAccounts_Template.xlsx",
)

MIGRATION_TABLE_ORDER = (
    "users",
    "reporting_periods",
    "member_types",
    "members",
    "dues",
    "events",
    "messages",
    "subscription_charges",
    "dining_charges",
    "payments",
    "ledger_categories",
    "bank_transactions",
    "bank_transaction_allocations",
    "meetings",
    "cashbook_entries",
    "bookings",
)

BANK_CATEGORY_DEFINITIONS = [
    ("CASH", "Cash", "in", 10),
    ("PRE_SUBS", "Pre-Subs", "in", 20),
    ("PRE_DINING", "Pre-Dining", "in", 30),
    ("SUBS", "Subs", "in", 40),
    ("DINING", "Dining", "in", 50),
    ("VISITOR", "Visitor", "in", 60),
    ("INITIATION", "Initiation", "in", 70),
    ("SUMUP", "SumUp", "in", 80),
    ("GAVEL", "Gavel", "in", 90),
    ("DONATIONS_IN", "Donations", "in", 100),
    ("CHAPTER_LOI", "Chapter LOI", "in", 110),
    ("LOI", "LOI", "in", 120),
    ("RELIEF", "Relief", "out", 130),
    ("DONATIONS_OUT", "Donations", "out", 140),
    ("UGLE", "UGLE", "out", 150),
    ("PGLE", "PGLE", "out", 160),
    ("ORSETT", "Orsett", "out", 170),
    ("WOOLMKT", "WoolMkt", "out", 180),
    ("CATERER", "Caterer", "out", 190),
    ("BANK_CHARGES", "Bank Charges", "out", 200),
    ("WIDOWS", "Widows", "out", 210),
]

VIRTUAL_ACCOUNT_DEFINITIONS = [
    ("MAIN", "Main", 10),
    ("CHARITY", "Charity", 20),
    ("GLASGOW", "Glasgow", 30),
    ("FRANK", "Frank", 40),
    ("LOI", "LOI", 50),
    ("SUBS", "Subs", 60),
    ("DINING", "Dining", 70),
    ("PRE_SUBS", "Pre-Paid Subs", 80),
    ("PRE_DINING", "Pre-Paid Dining", 90),
    ("BENEVOLENT", "Benevolent Fund", 100),
    ("CENTENARY", "Centeneraty Fund", 110),
]

VIRTUAL_ACCOUNT_CATEGORY_MAP = {
    "MAIN": ["CASH", "INITIATION", "SUMUP", "BANK_CHARGES"],
    "CHARITY": ["DONATIONS_IN", "DONATIONS_OUT"],
    "GLASGOW": ["UGLE", "PGLE"],
    "FRANK": ["ORSETT", "WOOLMKT", "CATERER"],
    "LOI": ["LOI", "CHAPTER_LOI"],
    "SUBS": ["SUBS"],
    "DINING": ["DINING", "VISITOR"],
    "PRE_SUBS": ["PRE_SUBS"],
    "PRE_DINING": ["PRE_DINING"],
    "BENEVOLENT": ["RELIEF", "WIDOWS"],
    "CENTENARY": ["GAVEL"],
}

BANK_COLUMN_CATEGORY_CODES = {
    "L": "CASH",
    "M": "PRE_SUBS",
    "N": "PRE_DINING",
    "O": "SUBS",
    "P": "DINING",
    "Q": "VISITOR",
    "R": "INITIATION",
    "S": "SUMUP",
    "T": "GAVEL",
    "U": "DONATIONS_IN",
    "V": "CHAPTER_LOI",
    "W": "LOI",
    "Z": "RELIEF",
    "AA": "DONATIONS_OUT",
    "AB": "UGLE",
    "AC": "PGLE",
    "AD": "ORSETT",
    "AE": "WOOLMKT",
    "AF": "CATERER",
    "AG": "BANK_CHARGES",
    "AH": "WIDOWS",
}

AUTH_USER_DEFINITIONS = [
    ("lodgeadmin", "Lodge Admin", "changeme", "lodge_admin"),
    ("treasurer", "Lodge Treasurer", "changeme", "treasurer"),
    ("secretary", "Lodge Secretary", "changeme", "secretary"),
    ("helper", "Lodge Helper", "changeme", "helper"),
]

_MAIN_NS = "http://schemas.openxmlformats.org/spreadsheetml/2006/main"
_REL_NS = "http://schemas.openxmlformats.org/officeDocument/2006/relationships"
_PKG_REL_NS = "http://schemas.openxmlformats.org/package/2006/relationships"
_NS = {"main": _MAIN_NS, "rel": _REL_NS, "pkgrel": _PKG_REL_NS}


def ensure_instance_path(app) -> None:
    Path(app.instance_path).mkdir(parents=True, exist_ok=True)


def default_database_path() -> Path:
    configured = os.environ.get("TREASURER_DATABASE")
    if configured:
        return Path(configured)

    local_app_data = os.environ.get("LOCALAPPDATA")
    if local_app_data:
        return Path(local_app_data) / "Treasurer" / "Lodge.db"

    return _project_root() / "instance" / "Lodge.db"


def ensure_database_parent_path(database_path: Path) -> None:
    database_path.parent.mkdir(parents=True, exist_ok=True)


def _is_postgres_dsn(database_spec: str) -> bool:
    return database_spec.startswith(("postgresql://", "postgres://"))


def _schema_sql_for_backend(db: "DatabaseHandle", sql: str) -> str:
    if db.backend != "sqlite":
        return sql

    return (
        re.sub(r"CREATE TABLE (?!IF NOT EXISTS)", "CREATE TABLE IF NOT EXISTS ", sql)
        .replace("INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", "INTEGER PRIMARY KEY AUTOINCREMENT")
        .replace("CURRENT_TIMESTAMP::text", "CURRENT_TIMESTAMP")
        .replace("CREATE INDEX ", "CREATE INDEX IF NOT EXISTS ")
    )


def _translate_placeholders(sql: str) -> str:
    return sql.replace("?", "%s")


class DatabaseHandle:
    def __init__(self, connection, backend: str):
        self._connection = connection
        self.backend = backend

    def execute(self, sql: str, params: tuple | list | None = None):
        if self.backend == "postgres":
            sql = _translate_placeholders(sql)
            if params is None:
                return self._connection.execute(sql)
            return self._connection.execute(sql, tuple(params))
        if params is None:
            return self._connection.execute(sql)
        return self._connection.execute(sql, params)

    def executemany(self, sql: str, params_seq):
        if self.backend == "postgres":
            sql = _translate_placeholders(sql)
            with self._connection.cursor() as cursor:
                return cursor.executemany(sql, [tuple(params) for params in params_seq])
        return self._connection.executemany(sql, params_seq)

    def executescript(self, script: str):
        if self.backend == "postgres":
            statements = [statement.strip() for statement in script.split(";") if statement.strip()]
            result = None
            for statement in statements:
                result = self._connection.execute(statement)
            return result
        return self._connection.executescript(script)

    def commit(self) -> None:
        self._connection.commit()

    def close(self) -> None:
        self._connection.close()

    def __getattr__(self, name):
        return getattr(self._connection, name)


def get_db() -> DatabaseHandle:
    if "db" not in g:
        database_spec = current_app.config["DATABASE"]
        if _is_postgres_dsn(database_spec):
            connection = psycopg.connect(database_spec, row_factory=dict_row)
            g.db = DatabaseHandle(connection, "postgres")
        else:
            connection = sqlite3.connect(database_spec)
            connection.row_factory = sqlite3.Row
            g.db = DatabaseHandle(connection, "sqlite")
    return g.db


def table_exists(db: DatabaseHandle, table_name: str) -> bool:
    if db.backend == "postgres":
        row = db.execute("SELECT to_regclass(?) AS table_name", (f"public.{table_name}",)).fetchone()
        return bool(row and row["table_name"])
    row = db.execute(
        "SELECT name FROM sqlite_master WHERE type='table' AND name=?",
        (table_name,),
    ).fetchone()
    return row is not None


def close_db(_error=None) -> None:
    db = g.pop("db", None)
    if db is not None:
        db.close()


def _project_root() -> Path:
    return Path(__file__).resolve().parent.parent


def _candidate_workbook_paths() -> list[Path]:
    root = _project_root()
    return [root / name for name in WORKBOOK_CANDIDATES]


def _find_existing_workbook() -> Path | None:
    for path in _candidate_workbook_paths():
        if path.exists():
            return path
    return None


def _candidate_statement_csv_paths() -> list[Path]:
    root = _project_root()
    return sorted(
        [
            path
            for path in root.glob("Transactions_Export*.csv")
            if path.is_file()
        ],
        key=lambda path: path.name.lower(),
    )


def _normalize_statement_text(raw_value: str | None) -> str:
    if raw_value is None:
        return ""
    return re.sub(r"\s+", " ", str(raw_value)).strip().upper()


def _tokenize_match_text(raw_value: str | None) -> set[str]:
    normalized = _normalize_statement_text(raw_value)
    return {token for token in re.split(r"[^A-Z0-9]+", normalized) if token}


def _parse_statement_date(raw_value: str | None) -> str | None:
    if not raw_value:
        return None

    value = str(raw_value).strip()
    for format_string in ("%d/%m/%Y", "%Y-%m-%d"):
        try:
            return datetime.strptime(value, format_string).date().isoformat()
        except ValueError:
            continue
    return value


def _parse_statement_amount(raw_value: str | None) -> float:
    if raw_value in (None, ""):
        return 0.0
    return round(float(str(raw_value).replace(",", "").strip()), 2)


def _bank_transaction_match_query(
    db: sqlite3.Connection,
    transaction_date: str | None,
    details: str,
    transaction_type: str | None,
    money_in: float,
    money_out: float,
    running_balance: float | None,
) -> sqlite3.Row | None:
    if running_balance is None:
        balance_clause = "bt.running_balance IS NULL"
        balance_params: tuple[object, ...] = ()
    else:
        balance_clause = "ROUND(CAST(bt.running_balance AS numeric), 2) = ?"
        balance_params = (round(float(running_balance), 2),)

    query = f"""
        SELECT *
        FROM bank_transactions bt
        WHERE COALESCE(bt.transaction_date, '') = ?
          AND UPPER(TRIM(bt.details)) = ?
          AND COALESCE(UPPER(TRIM(bt.transaction_type)), '') = ?
          AND ROUND(CAST(bt.money_in AS numeric), 2) = ?
          AND ROUND(CAST(bt.money_out AS numeric), 2) = ?
          AND {balance_clause}
        ORDER BY bt.id ASC
        LIMIT 1
    """
    return db.execute(
        query,
        (
            transaction_date or "",
            _normalize_statement_text(details),
            _normalize_statement_text(transaction_type),
            round(money_in, 2),
            round(money_out, 2),
            *balance_params,
        ),
    ).fetchone()


def _score_bank_transaction_match(
    target_date: str | None,
    details: str,
    transaction_type: str | None,
    candidate: dict[str, object],
) -> float:
    score = 0.0
    target_details = _normalize_statement_text(details)
    candidate_details = _normalize_statement_text(candidate.get("details"))
    target_type = _normalize_statement_text(transaction_type)
    candidate_type = _normalize_statement_text(candidate.get("transaction_type"))

    if target_details and candidate_details:
        if target_details == candidate_details:
            score += 100.0
        else:
            ratio = difflib.SequenceMatcher(None, target_details, candidate_details).ratio()
            score += ratio * 60.0

        target_tokens = _tokenize_match_text(details)
        candidate_tokens = _tokenize_match_text(candidate.get("details"))
        if target_tokens and candidate_tokens:
            overlap = len(target_tokens & candidate_tokens) / len(target_tokens | candidate_tokens)
            score += overlap * 40.0

    if target_type and candidate_type:
        if target_type == candidate_type:
            score += 20.0
        else:
            score -= 10.0

    candidate_date = candidate.get("transaction_date")
    if target_date and candidate_date:
        try:
            target_dt = datetime.strptime(target_date, "%Y-%m-%d").date()
            candidate_dt = datetime.strptime(str(candidate_date), "%Y-%m-%d").date()
            day_gap = abs((target_dt - candidate_dt).days)
            score += max(0.0, 15.0 - min(day_gap, 15))
        except ValueError:
            pass

    if candidate.get("money_in") is not None and candidate.get("money_out") is not None:
        target_money = float(candidate.get("money_in") or 0) + float(candidate.get("money_out") or 0)
        score += max(0.0, 5.0 - abs(target_money - (float(candidate.get("money_in") or 0) + float(candidate.get("money_out") or 0))))

    return score


def _upsert_bank_transaction(
    db: sqlite3.Connection,
    reporting_period_id: int,
    *,
    source_workbook: str,
    source_sheet: str,
    source_row_number: int,
    transaction_date: str | None,
    details: str,
    transaction_type: str | None,
    money_in: float,
    money_out: float,
    running_balance: float | None,
    is_opening_balance: int = 0,
) -> str:
    existing = db.execute(
        """
        SELECT id
        FROM bank_transactions
        WHERE source_workbook = ?
          AND source_sheet = ?
          AND source_row_number = ?
        LIMIT 1
        """,
        (source_workbook, source_sheet, source_row_number),
    ).fetchone()

    if existing is None:
        existing = _bank_transaction_match_query(
            db,
            transaction_date,
            details,
            transaction_type,
            money_in,
            money_out,
            running_balance,
        )

    if existing is None:
        db.execute(
            """
            INSERT INTO bank_transactions (
                reporting_period_id,
                transaction_date,
                details,
                transaction_type,
                money_in,
                money_out,
                running_balance,
                is_opening_balance,
                source_workbook,
                source_sheet,
                source_row_number
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                reporting_period_id,
                transaction_date,
                details,
                transaction_type,
                round(money_in, 2),
                round(money_out, 2),
                running_balance,
                is_opening_balance,
                source_workbook,
                source_sheet,
                source_row_number,
            ),
        )
        return "inserted"

    db.execute(
        """
        UPDATE bank_transactions
        SET
            reporting_period_id = ?,
            transaction_date = ?,
            details = ?,
            transaction_type = ?,
            money_in = ?,
            money_out = ?,
            running_balance = ?,
            is_opening_balance = ?,
            source_workbook = ?,
            source_sheet = ?,
            source_row_number = ?
        WHERE id = ?
        """,
        (
            reporting_period_id,
            transaction_date,
            details,
            transaction_type,
            round(money_in, 2),
            round(money_out, 2),
            running_balance,
            is_opening_balance,
            source_workbook,
            source_sheet,
            source_row_number,
            existing["id"],
        ),
    )
    return "updated"


def _import_bank_statement_csv(
    db: sqlite3.Connection,
    reporting_period_id: int,
    csv_path: Path,
) -> dict[str, int]:
    inserted = 0
    updated = 0

    with csv_path.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        for row_number, row in enumerate(reader, start=2):
            if not row:
                continue

            transaction_date = _parse_statement_date(row.get("Date"))
            details = (row.get("Details") or "").strip()
            transaction_type = (row.get("Transaction Type") or "").strip() or None
            money_in = _parse_statement_amount(row.get("In"))
            money_out = _parse_statement_amount(row.get("Out"))
            running_balance = _parse_statement_amount(row.get("Balance"))

            if (
                not transaction_date
                and not details
                and transaction_type is None
                and money_in == 0
                and money_out == 0
                and running_balance == 0
            ):
                continue

            action = _upsert_bank_transaction(
                db,
                reporting_period_id,
                source_workbook=csv_path.name,
                source_sheet="CSV",
                source_row_number=row_number,
                transaction_date=transaction_date,
                details=details or "Imported statement row",
                transaction_type=transaction_type,
                money_in=money_in,
                money_out=money_out,
                running_balance=running_balance,
            )

            if action == "inserted":
                inserted += 1
            else:
                updated += 1

    return {"inserted": inserted, "updated": updated}


def import_bank_statement_exports(
    db: sqlite3.Connection,
    reporting_period_id: int = 1,
    statement_paths: list[Path] | None = None,
) -> dict[str, int]:
    paths = statement_paths if statement_paths is not None else _candidate_statement_csv_paths()
    totals = {"files": 0, "inserted": 0, "updated": 0}

    for path in paths:
        if not path.exists() or not path.is_file():
            continue
        file_totals = _import_bank_statement_csv(db, reporting_period_id, path)
        totals["files"] += 1
        totals["inserted"] += file_totals["inserted"]
        totals["updated"] += file_totals["updated"]

    return totals


def _excel_serial_to_iso_date(raw_value: str | None) -> str | None:
    if not raw_value:
        return None
    serial = int(float(raw_value))
    return (date(1899, 12, 30) + timedelta(days=serial)).isoformat()


def _to_amount(raw_value: str | None) -> float:
    if raw_value in (None, ""):
        return 0.0
    return round(float(raw_value), 2)


def _load_shared_strings(archive: zipfile.ZipFile) -> list[str]:
    shared_strings: list[str] = []
    path = "xl/sharedStrings.xml"
    if path not in archive.namelist():
        return shared_strings

    root = ET.fromstring(archive.read(path))
    for item in root.findall(f"{{{_MAIN_NS}}}si"):
        shared_strings.append("".join(node.text or "" for node in item.iter(f"{{{_MAIN_NS}}}t")))
    return shared_strings


def _get_cell_value(cell: ET.Element, shared_strings: list[str]) -> str:
    cell_type = cell.attrib.get("t")

    if cell_type == "inlineStr":
        text_node = cell.find(f"{{{_MAIN_NS}}}is")
        return "" if text_node is None else "".join(node.text or "" for node in text_node.iter(f"{{{_MAIN_NS}}}t"))

    value_node = cell.find(f"{{{_MAIN_NS}}}v")
    if value_node is None or value_node.text is None:
        return ""

    if cell_type == "s":
        return shared_strings[int(value_node.text)]

    return value_node.text


def _sheet_target_by_name(archive: zipfile.ZipFile, sheet_name: str) -> str | None:
    workbook = ET.fromstring(archive.read("xl/workbook.xml"))
    relationships = ET.fromstring(archive.read("xl/_rels/workbook.xml.rels"))
    relationship_map = {
        relationship.attrib["Id"]: relationship.attrib["Target"]
        for relationship in relationships.findall(f"{{{_PKG_REL_NS}}}Relationship")
    }

    sheets = workbook.find("main:sheets", _NS)
    if sheets is None:
        return None

    for sheet in sheets.findall("main:sheet", _NS):
        if sheet.attrib.get("name") == sheet_name:
            relationship_id = sheet.attrib.get(f"{{{_REL_NS}}}id")
            if relationship_id:
                return relationship_map.get(relationship_id)
    return None


def _read_sheet_rows(workbook_path: Path, sheet_name: str) -> list[tuple[int, dict[str, str]]]:
    with zipfile.ZipFile(workbook_path) as archive:
        target = _sheet_target_by_name(archive, sheet_name)
        if target is None:
            return []

        shared_strings = _load_shared_strings(archive)
        sheet_xml = ET.fromstring(archive.read(f"xl/{target}"))
        sheet_data = sheet_xml.find(f"{{{_MAIN_NS}}}sheetData")
        if sheet_data is None:
            return []

        rows: list[tuple[int, dict[str, str]]] = []
        for row in sheet_data.findall(f"{{{_MAIN_NS}}}row"):
            row_number = int(row.attrib["r"])
            values: dict[str, str] = {}
            for cell in row.findall(f"{{{_MAIN_NS}}}c"):
                reference = cell.attrib.get("r", "")
                column = re.match(r"[A-Z]+", reference)
                if column is None:
                    continue
                values[column.group(0)] = _get_cell_value(cell, shared_strings)
            rows.append((row_number, values))
        return rows


def seed_ledger_categories(db: sqlite3.Connection) -> None:
    db.executemany(
        """
        INSERT INTO ledger_categories (code, display_name, direction, sort_order)
        VALUES (?, ?, ?, ?)
        ON CONFLICT (code) DO NOTHING
        """,
        BANK_CATEGORY_DEFINITIONS,
    )


def seed_virtual_accounts(db: sqlite3.Connection) -> None:
    db.executemany(
        """
        INSERT INTO virtual_accounts (code, display_name, sort_order)
        VALUES (?, ?, ?)
        ON CONFLICT (code) DO NOTHING
        """,
        VIRTUAL_ACCOUNT_DEFINITIONS,
    )


def seed_virtual_account_category_map(db: sqlite3.Connection) -> None:
    account_ids = {
        row["code"]: row["id"]
        for row in db.execute("SELECT id, code FROM virtual_accounts").fetchall()
    }
    category_ids = {
        row["code"]: row["id"]
        for row in db.execute("SELECT id, code FROM ledger_categories").fetchall()
    }
    mappings: list[tuple[int, int]] = []
    for account_code, category_codes in VIRTUAL_ACCOUNT_CATEGORY_MAP.items():
        account_id = account_ids.get(account_code)
        if account_id is None:
            continue
        for category_code in category_codes:
            category_id = category_ids.get(category_code)
            if category_id is None:
                continue
            mappings.append((account_id, category_id))

    db.execute("DELETE FROM virtual_account_category_map")

    db.executemany(
        """
        INSERT INTO virtual_account_category_map (virtual_account_id, ledger_category_id)
        VALUES (?, ?)
        """,
        mappings,
    )


def ensure_financial_tables(db: sqlite3.Connection) -> None:
    schema_sql = _schema_sql_for_backend(
        db,
        """
        CREATE TABLE IF NOT EXISTS ledger_categories (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code TEXT NOT NULL UNIQUE,
            display_name TEXT NOT NULL,
            direction TEXT NOT NULL,
            sort_order INTEGER NOT NULL DEFAULT 0,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
        );

        CREATE TABLE IF NOT EXISTS bank_transactions (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            reporting_period_id INTEGER NOT NULL,
            transaction_date TEXT,
            details TEXT NOT NULL,
            transaction_type TEXT,
            money_in REAL NOT NULL DEFAULT 0,
            money_out REAL NOT NULL DEFAULT 0,
            running_balance REAL,
            is_opening_balance INTEGER NOT NULL DEFAULT 0,
            source_workbook TEXT,
            source_sheet TEXT,
            source_row_number INTEGER,
            notes TEXT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
            FOREIGN KEY (reporting_period_id) REFERENCES reporting_periods (id),
            UNIQUE (source_workbook, source_sheet, source_row_number)
        );

        CREATE TABLE IF NOT EXISTS bank_transaction_allocations (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            bank_transaction_id INTEGER NOT NULL,
            ledger_category_id INTEGER NOT NULL,
            amount REAL NOT NULL,
            notes TEXT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
            FOREIGN KEY (bank_transaction_id) REFERENCES bank_transactions (id) ON DELETE CASCADE,
            FOREIGN KEY (ledger_category_id) REFERENCES ledger_categories (id)
        );

        CREATE TABLE IF NOT EXISTS meetings (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            reporting_period_id INTEGER NOT NULL,
            meeting_key TEXT NOT NULL UNIQUE,
            meeting_name TEXT NOT NULL,
            meeting_date TEXT,
            meeting_type TEXT NOT NULL DEFAULT 'Regular',
            sort_order INTEGER NOT NULL DEFAULT 0,
            notes TEXT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
            FOREIGN KEY (reporting_period_id) REFERENCES reporting_periods (id)
        );

        CREATE TABLE IF NOT EXISTS cashbook_entries (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            reporting_period_id INTEGER NOT NULL,
            meeting_key TEXT NOT NULL CHECK (meeting_key IN ('SEPTEMBER', 'NOVEMBER', 'JANUARY', 'MARCH', 'MAY')),
            entry_type TEXT NOT NULL,
            entry_name TEXT NOT NULL,
            member_id INTEGER,
            ledger_category_id INTEGER,
            money_in REAL NOT NULL DEFAULT 0,
            money_out REAL NOT NULL DEFAULT 0,
            notes TEXT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
            FOREIGN KEY (reporting_period_id) REFERENCES reporting_periods (id),
            FOREIGN KEY (member_id) REFERENCES members (id),
            FOREIGN KEY (ledger_category_id) REFERENCES ledger_categories (id)
        );

        CREATE TABLE IF NOT EXISTS virtual_accounts (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code TEXT NOT NULL UNIQUE,
            display_name TEXT NOT NULL,
            sort_order INTEGER NOT NULL DEFAULT 0,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
        );

        CREATE TABLE IF NOT EXISTS virtual_account_balances (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            reporting_period_id INTEGER NOT NULL,
            virtual_account_id INTEGER NOT NULL,
            opening_balance REAL NOT NULL DEFAULT 0,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
            FOREIGN KEY (reporting_period_id) REFERENCES reporting_periods (id),
            FOREIGN KEY (virtual_account_id) REFERENCES virtual_accounts (id),
            UNIQUE (reporting_period_id, virtual_account_id)
        );

        CREATE TABLE IF NOT EXISTS virtual_account_category_map (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            virtual_account_id INTEGER NOT NULL,
            ledger_category_id INTEGER NOT NULL UNIQUE,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
            FOREIGN KEY (virtual_account_id) REFERENCES virtual_accounts (id),
            FOREIGN KEY (ledger_category_id) REFERENCES ledger_categories (id)
        );

        CREATE INDEX IF NOT EXISTS idx_bank_transactions_date ON bank_transactions (transaction_date);
        CREATE INDEX IF NOT EXISTS idx_bank_transactions_reporting_period_id ON bank_transactions (reporting_period_id);
        CREATE INDEX IF NOT EXISTS idx_bank_transaction_allocations_transaction_id ON bank_transaction_allocations (bank_transaction_id);
        CREATE INDEX IF NOT EXISTS idx_bank_transaction_allocations_category_id ON bank_transaction_allocations (ledger_category_id);
        CREATE INDEX IF NOT EXISTS idx_meetings_reporting_period_id ON meetings (reporting_period_id);
        CREATE INDEX IF NOT EXISTS idx_meetings_sort_order ON meetings (sort_order);
        CREATE INDEX IF NOT EXISTS idx_cashbook_entries_meeting_key ON cashbook_entries (meeting_key);
        CREATE INDEX IF NOT EXISTS idx_virtual_account_balances_reporting_period_id ON virtual_account_balances (reporting_period_id);
        """
    )
    db.executescript(
        schema_sql
    )


def _category_id_map(db: sqlite3.Connection) -> dict[str, int]:
    return {
        row["code"]: row["id"]
        for row in db.execute("SELECT id, code FROM ledger_categories").fetchall()
    }


def _dues_status(
    subscription_due: float,
    subscription_paid: float,
    dining_due: float,
    dining_paid: float,
    member_code: str,
) -> str:
    outstanding = (subscription_due - subscription_paid) + (dining_due - dining_paid)
    if member_code in {"EXCLUDE", "DECEASED"}:
        return "written-off"
    if member_code == "RESIGNED" and outstanding > 0:
        return "written-off"
    if outstanding <= 0:
        return "paid"
    if subscription_paid > 0 or dining_paid > 0:
        return "part-paid"
    return "unpaid"


def seed_meeting_schedule(db: sqlite3.Connection, reporting_period_id: int = 1) -> None:
    meeting_rows = [
        ("SEPTEMBER", "September Meeting", "2025-09-15", "Regular", 1, ""),
        ("NOVEMBER", "November Meeting", "2025-11-17", "Regular", 2, ""),
        ("JANUARY", "January Meeting", "2026-01-19", "Regular", 3, ""),
        ("MARCH", "March Meeting", "2026-03-16", "Regular", 4, ""),
        ("MAY", "Installation Meeting", "2026-05-18", "Installation", 5, ""),
    ]

    db.executemany(
        """
        INSERT INTO meetings (
            reporting_period_id, meeting_key, meeting_name, meeting_date, meeting_type, sort_order, notes
        )
        VALUES (?, ?, ?, ?, ?, ?, ?)
        ON CONFLICT (meeting_key) DO NOTHING
        """,
        [
            (reporting_period_id, key, name, meeting_date, meeting_type, sort_order, notes)
            for key, name, meeting_date, meeting_type, sort_order, notes in meeting_rows
        ],
    )


def seed_virtual_account_balances(db: sqlite3.Connection, reporting_period_id: int = 1) -> None:
    virtual_accounts = db.execute("SELECT id FROM virtual_accounts").fetchall()
    if not virtual_accounts:
        return

    db.executemany(
        """
        INSERT INTO virtual_account_balances (reporting_period_id, virtual_account_id, opening_balance)
        VALUES (?, ?, 0)
        ON CONFLICT (reporting_period_id, virtual_account_id) DO NOTHING
        """,
        [(reporting_period_id, row["id"]) for row in virtual_accounts],
    )


def import_bank_transactions_from_workbook(
    db: sqlite3.Connection,
    reporting_period_id: int,
    workbook_path: Path,
) -> int:
    rows = _read_sheet_rows(workbook_path, WORKBOOK_BANK_SHEET)
    if not rows:
        return 0

    category_ids = _category_id_map(db)
    imported = 0

    for row_number, row in rows[1:]:
        row_label = row.get("A", "").strip()
        details = row.get("B", "").strip()
        transaction_type = row.get("C", "").strip()

        if row_label == "TOTALS" or details == "TOTALS":
            break

        if not details and not transaction_type and not row.get("D") and not row.get("E"):
            continue

        transaction_date = _excel_serial_to_iso_date(row.get("A"))
        money_in = _to_amount(row.get("D"))
        money_out = _to_amount(row.get("E"))
        running_balance = row.get("F")

        action = _upsert_bank_transaction(
            db,
            reporting_period_id,
            source_workbook=workbook_path.name,
            source_sheet=WORKBOOK_BANK_SHEET,
            source_row_number=row_number,
            transaction_date=transaction_date,
            details=details or "Imported transaction",
            transaction_type=transaction_type or None,
            money_in=money_in,
            money_out=money_out,
            running_balance=float(running_balance) if running_balance not in (None, "") else None,
            is_opening_balance=1 if details == "Opening Balance" else 0,
        )

        if action == "inserted":
            bank_transaction = db.execute(
                """
                SELECT id
                FROM bank_transactions
                WHERE source_workbook = ? AND source_sheet = ? AND source_row_number = ?
                LIMIT 1
                """,
                (workbook_path.name, WORKBOOK_BANK_SHEET, row_number),
            ).fetchone()
            bank_transaction_id = bank_transaction["id"] if bank_transaction else None
            if bank_transaction_id is not None:
                for column, category_code in BANK_COLUMN_CATEGORY_CODES.items():
                    amount = _to_amount(row.get(column))
                    if amount == 0:
                        continue
                    db.execute(
                        """
                        INSERT INTO bank_transaction_allocations (
                            bank_transaction_id, ledger_category_id, amount
                        )
                        VALUES (?, ?, ?)
                        """,
                        (bank_transaction_id, category_ids[category_code], amount),
                    )
            imported += 1

    return imported


def replace_bank_transaction_allocations(
    db: sqlite3.Connection,
    bank_transaction_id: int,
    allocations: list[tuple[int, float]],
) -> None:
    db.execute(
        "DELETE FROM bank_transaction_allocations WHERE bank_transaction_id = ?",
        (bank_transaction_id,),
    )
    db.executemany(
        """
        INSERT INTO bank_transaction_allocations (bank_transaction_id, ledger_category_id, amount)
        VALUES (?, ?, ?)
        """,
        [
            (bank_transaction_id, ledger_category_id, amount)
            for ledger_category_id, amount in allocations
        ],
    )


def import_bank_transactions(db: sqlite3.Connection, reporting_period_id: int = 1) -> int:
    ensure_financial_tables(db)
    seed_ledger_categories(db)
    workbook_path = _find_existing_workbook()
    if workbook_path is None:
        return 0
    return import_bank_transactions_from_workbook(db, reporting_period_id, workbook_path)


def seed_bank_transactions_from_payments(
    db: sqlite3.Connection,
    reporting_period_id: int,
) -> int:
    category_ids = _category_id_map(db)
    payment_rows = db.execute(
        """
        SELECT
            p.id,
            p.payment_date,
            p.payment_method,
            p.reference,
            p.total_amount,
            p.subscription_amount,
            p.dining_amount,
            m.full_name
        FROM payments p
        JOIN members m ON m.id = p.member_id
        WHERE p.reporting_period_id = ?
        ORDER BY p.payment_date, p.id
        """,
        (reporting_period_id,),
    ).fetchall()

    for payment in payment_rows:
        bank_transaction = db.execute(
            """
            INSERT INTO bank_transactions (
                reporting_period_id,
                transaction_date,
                details,
                transaction_type,
                money_in,
                money_out,
                source_workbook,
                source_sheet,
                source_row_number,
                notes
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            RETURNING id
            """,
            (
                reporting_period_id,
                payment["payment_date"],
                f'{payment["full_name"]} payment',
                payment["payment_method"],
                float(payment["total_amount"]),
                0.0,
                "system",
                "payments",
                int(payment["id"]),
                payment["reference"],
            ),
        ).fetchone()
        bank_transaction_id = bank_transaction["id"]

        if payment["subscription_amount"] > 0:
            db.execute(
                """
                INSERT INTO bank_transaction_allocations (
                    bank_transaction_id, ledger_category_id, amount
                )
                VALUES (?, ?, ?)
                """,
                (bank_transaction_id, category_ids["SUBS"], float(payment["subscription_amount"])),
            )
        if payment["dining_amount"] > 0:
            db.execute(
                """
                INSERT INTO bank_transaction_allocations (
                    bank_transaction_id, ledger_category_id, amount
                )
                VALUES (?, ?, ?)
                """,
                (bank_transaction_id, category_ids["DINING"], float(payment["dining_amount"])),
            )

    return len(payment_rows)


def seed_bank_ledger(db: sqlite3.Connection, reporting_period_id: int = 1) -> int:
    if db.execute("SELECT COUNT(*) AS total FROM bank_transactions").fetchone()["total"] > 0:
        return 0

    csv_totals = import_bank_statement_exports(db, reporting_period_id)
    if csv_totals["inserted"] > 0 or csv_totals["updated"] > 0:
        return csv_totals["inserted"] + csv_totals["updated"]

    workbook_path = _find_existing_workbook()
    if workbook_path is not None:
        imported = import_bank_transactions_from_workbook(db, reporting_period_id, workbook_path)
        if imported > 0:
            return imported

    return seed_bank_transactions_from_payments(db, reporting_period_id)


def _current_reporting_period_id(db: sqlite3.Connection) -> int:
    row = db.execute(
        "SELECT id FROM reporting_periods WHERE is_current = 1 ORDER BY id DESC LIMIT 1"
    ).fetchone()
    return row["id"] if row else 1


def virtual_account_report(db: sqlite3.Connection, reporting_period_id: int | None = None) -> list[dict[str, object]]:
    reporting_period_id = reporting_period_id or _current_reporting_period_id(db)
    account_rows = db.execute(
        """
        SELECT
            va.id,
            va.code,
            va.display_name,
            va.sort_order,
            COALESCE(vab.opening_balance, 0) AS opening_balance
        FROM virtual_accounts va
        LEFT JOIN virtual_account_balances vab
          ON vab.virtual_account_id = va.id
         AND vab.reporting_period_id = ?
        ORDER BY va.sort_order, va.display_name
        """,
        (reporting_period_id,),
    ).fetchall()

    category_map = {
        row["ledger_category_id"]: row["virtual_account_code"]
        for row in db.execute(
            """
            SELECT vacm.ledger_category_id, va.code AS virtual_account_code
            FROM virtual_account_category_map vacm
            JOIN virtual_accounts va ON va.id = vacm.virtual_account_id
            """
        ).fetchall()
    }

    account_index = {
        row["code"]: {
            "code": row["code"],
            "display_name": row["display_name"],
            "sort_order": row["sort_order"],
            "opening_balance": float(row["opening_balance"] or 0),
            "total_in": 0.0,
            "total_out": 0.0,
            "closing_balance": float(row["opening_balance"] or 0),
            "entries": [],
        }
        for row in account_rows
    }

    if "MAIN" not in account_index:
        account_index["MAIN"] = {
            "code": "MAIN",
            "display_name": "Main",
            "sort_order": 10,
            "opening_balance": 0.0,
            "total_in": 0.0,
            "total_out": 0.0,
            "closing_balance": 0.0,
            "entries": [],
        }

    entry_rows = db.execute(
        """
        SELECT
            bt.id AS bank_transaction_id,
            bt.transaction_date,
            bt.details,
            bt.transaction_type,
            lc.id AS ledger_category_id,
            lc.code AS ledger_category_code,
            lc.display_name AS ledger_category_name,
            lc.direction,
            bta.amount
        FROM bank_transaction_allocations bta
        JOIN bank_transactions bt ON bt.id = bta.bank_transaction_id
        JOIN ledger_categories lc ON lc.id = bta.ledger_category_id
        WHERE bt.reporting_period_id = ?
        ORDER BY
            CASE WHEN bt.transaction_date IS NULL OR bt.transaction_date = '' THEN 1 ELSE 0 END,
            bt.transaction_date,
            bt.id,
            bta.id
        """,
        (reporting_period_id,),
    ).fetchall()

    for row in entry_rows:
        account_code = category_map.get(row["ledger_category_id"], "MAIN")
        if account_code not in account_index:
            account_index[account_code] = {
                "code": account_code,
                "display_name": account_code.title(),
                "sort_order": 999,
                "opening_balance": 0.0,
                "total_in": 0.0,
                "total_out": 0.0,
                "closing_balance": 0.0,
                "entries": [],
            }
        amount = float(row["amount"] or 0)
        is_income = row["direction"] == "in"
        account = account_index[account_code]
        if is_income:
            account["total_in"] += amount
        else:
            account["total_out"] += amount
        account["entries"].append(
            {
                "bank_transaction_id": row["bank_transaction_id"],
                "transaction_date": row["transaction_date"],
                "details": row["details"],
                "transaction_type": row["transaction_type"],
                "category_code": row["ledger_category_code"],
                "category_name": row["ledger_category_name"],
                "direction": row["direction"],
                "amount": amount,
            }
        )

    for account in account_index.values():
        account["closing_balance"] = account["opening_balance"] + account["total_in"] - account["total_out"]

    return sorted(account_index.values(), key=lambda item: (item["sort_order"], item["display_name"]))


def backfill_bank_allocations_from_workbook(
    db: sqlite3.Connection,
    reporting_period_id: int = 1,
    workbook_path: Path | None = None,
) -> dict[str, int]:
    workbook_path = workbook_path or _find_existing_workbook()
    if workbook_path is None:
        return {"rows_seen": 0, "transactions_matched": 0, "allocations_written": 0}

    rows = _read_sheet_rows(workbook_path, WORKBOOK_BANK_SHEET)
    if not rows:
        return {"rows_seen": 0, "transactions_matched": 0, "allocations_written": 0}

    db.execute("DELETE FROM bank_transaction_allocations")
    category_ids = _category_id_map(db)
    rows_seen = 0
    transactions_matched = 0
    allocations_written = 0

    for row_number, row in rows[1:]:
        row_label = row.get("A", "").strip()
        details = row.get("B", "").strip()
        transaction_type = row.get("C", "").strip()

        if row_label == "TOTALS" or details == "TOTALS":
            break

        transaction_date = _excel_serial_to_iso_date(row.get("A"))
        money_in = _to_amount(row.get("D"))
        money_out = _to_amount(row.get("E"))
        running_balance = row.get("F")

        if money_in > 0:
            candidate_rows = db.execute(
                """
                SELECT id, transaction_date, details, transaction_type, money_in, money_out, running_balance
                FROM bank_transactions
                WHERE ROUND(CAST(money_in AS numeric), 2) = ?
                ORDER BY id
                """,
                (money_in,),
            ).fetchall()
        else:
            candidate_rows = db.execute(
                """
                SELECT id, transaction_date, details, transaction_type, money_in, money_out, running_balance
                FROM bank_transactions
                WHERE ROUND(CAST(money_out AS numeric), 2) = ?
                ORDER BY id
                """,
                (money_out,),
            ).fetchall()

        if transaction_type:
            filtered_candidates = [
                candidate
                for candidate in candidate_rows
                if _normalize_statement_text(candidate["transaction_type"])
                == _normalize_statement_text(transaction_type)
            ]
            if filtered_candidates:
                candidate_rows = filtered_candidates

        best_candidate = None
        best_score = 0.0
        for candidate in candidate_rows:
            score = _score_bank_transaction_match(
                transaction_date,
                details or "Imported transaction",
                transaction_type or None,
                candidate,
            )
            if score > best_score:
                best_score = score
                best_candidate = candidate

        matched_transaction = best_candidate if best_score >= 35.0 else None
        rows_seen += 1

        if matched_transaction is None:
            continue

        allocations: list[tuple[int, float]] = []
        for column, category_code in BANK_COLUMN_CATEGORY_CODES.items():
            amount = _to_amount(row.get(column))
            if amount == 0:
                continue
            allocations.append((category_ids[category_code], amount))

        if allocations:
            replace_bank_transaction_allocations(db, matched_transaction["id"], allocations)
            allocations_written += len(allocations)
        transactions_matched += 1

    return {
        "rows_seen": rows_seen,
        "transactions_matched": transactions_matched,
        "allocations_written": allocations_written,
    }


def migrate_sqlite_database_to_postgres(sqlite_path: Path, postgres_dsn: str) -> dict[str, int]:
    if not sqlite_path.exists():
        raise FileNotFoundError(f"SQLite database not found: {sqlite_path}")

    sqlite_db = sqlite3.connect(str(sqlite_path))
    sqlite_db.row_factory = sqlite3.Row
    postgres_db = DatabaseHandle(psycopg.connect(postgres_dsn, row_factory=dict_row), "postgres")

    try:
        if table_exists(postgres_db, "users"):
            existing_users = postgres_db.execute("SELECT COUNT(*) AS total FROM users").fetchone()
            if existing_users and existing_users["total"]:
                raise RuntimeError("The PostgreSQL database already contains data.")

        schema_path = Path(__file__).with_name("schema.sql")
        postgres_db.executescript(schema_path.read_text(encoding="utf-8"))

        inserted_rows = 0
        for table_name in MIGRATION_TABLE_ORDER:
            column_rows = sqlite_db.execute(f"PRAGMA table_info({table_name})").fetchall()
            if not column_rows:
                continue

            column_names = [row["name"] for row in column_rows]
            select_sql = f"SELECT {', '.join(column_names)} FROM {table_name} ORDER BY id"
            rows = sqlite_db.execute(select_sql).fetchall()
            if rows:
                insert_sql = (
                    f"INSERT INTO {table_name} ({', '.join(column_names)}) "
                    f"VALUES ({', '.join(['%s'] * len(column_names))})"
                )
                postgres_db.executemany(
                    insert_sql,
                    [tuple(row[column] for column in column_names) for row in rows],
                )
                inserted_rows += len(rows)

            max_id_row = sqlite_db.execute(f"SELECT COALESCE(MAX(id), 0) AS max_id FROM {table_name}").fetchone()
            next_id = int(max_id_row["max_id"]) + 1 if max_id_row else 1
            postgres_db.execute(f"ALTER TABLE {table_name} ALTER COLUMN id RESTART WITH {next_id}")

        seed_ledger_categories(postgres_db)
        if table_exists(postgres_db, "reporting_periods"):
            seed_meeting_schedule(postgres_db, reporting_period_id=1)
        postgres_db.commit()
        return {"inserted_rows": inserted_rows}
    finally:
        sqlite_db.close()
        postgres_db.close()


def init_db() -> None:
    db = get_db()
    schema_path = Path(__file__).with_name("schema.sql")
    db.executescript(_schema_sql_for_backend(db, schema_path.read_text(encoding="utf-8")))

    seed_auth_users(db)

    db.execute(
        """
        INSERT INTO reporting_periods (label, start_date, end_date, is_current)
        VALUES (?, ?, ?, ?)
        """,
        ("2025-26", "2025-09-01", "2026-08-31", 1),
    )

    seed_meeting_schedule(db, reporting_period_id=1)

    db.executemany(
        """
        INSERT INTO member_types (
            code, description, subscription_rule, dining_rule,
            default_subscription_amount, default_dining_amount
        )
        VALUES (?, ?, ?, ?, ?, ?)
        """,
        [
            ("FULL", "Full member", "standard", "annual_package", 200.00, 125.00),
            ("ND", "Non-diner", "standard", "none", 200.00, 0.00),
            ("PAYG", "Pay as you go dining", "standard", "payg", 200.00, 0.00),
            ("SEC", "Secretary", "exempt", "annual_package", 0.00, 125.00),
            ("EXCLUDE", "Excluded or unrecoverable", "manual", "manual", 200.00, 0.00),
            ("RESIGNED", "Resigned member", "manual", "manual", 200.00, 0.00),
            ("DECEASED", "Deceased member", "manual", "none", 200.00, 0.00),
            ("VISITOR", "Visitor", "none", "payg", 0.00, 0.00),
        ],
    )

    member_rows = [
        ("*Visitor", "VISITOR", None, 0.00, 0.00, 0.00, 0.00, ""),
        ("Awcock,David", "FULL", None, 200.00, 200.00, 125.00, 125.00, ""),
        ("Bradley Brown", "FULL", None, 120.00, 120.00, 75.00, 75.00, ""),
        ("Chipperfield,David", "ND", None, 200.00, 200.00, 0.00, 0.00, ""),
        ("Coleridge,Ashley", "SEC", None, 0.00, 0.00, 0.00, 0.00, ""),
        ("Coleridge-Humphries,Connor", "ND", None, 200.00, 200.00, 150.00, 150.00, ""),
        ("Connolly,P.J", "EXCLUDE", None, 200.00, 0.00, 0.00, 0.00, "Spoke to his son, he has dementia, so this money is lost"),
        ("Featherstone,Allen", "ND", None, 200.00, 200.00, 0.00, 0.00, ""),
        ("Fulford,Len", "FULL", None, 200.00, 200.00, 125.00, 125.00, ""),
        ("Gillam,Mark", "PAYG", None, 200.00, 200.00, 0.00, 0.00, ""),
        ("Higgins, Nicolas", "FULL", None, 200.00, 200.00, 125.00, 125.00, ""),
        ("Holloway,Ian", "RESIGNED", None, 200.00, 0.00, 0.00, 0.00, "Resigned"),
        ("James,Ian", "PAYG", None, 400.00, 300.00, 0.00, 0.00, ""),
        ("Jess, Matthew", "FULL", None, 200.00, 200.00, 125.00, 125.00, ""),
        ("Marshall,Arthur", "ND", None, 200.00, 200.00, 0.00, 0.00, ""),
        ("Matondo, Herve", "RESIGNED", None, 200.00, 0.00, 0.00, 0.00, "Resigning - write off"),
        ("Moss,Peter", "FULL", None, 149.40, 149.40, 93.60, 93.60, ""),
        ("Mullender,Ray", "PAYG", None, 200.00, 200.00, 0.00, 0.00, ""),
        ("O'Brien,Keith", "FULL", None, 200.00, 200.00, 125.00, 125.00, ""),
        ("Pavey, Shaun", "FULL", None, 240.00, 0.00, 0.00, 0.00, "Reminder sent 4th Jan"),
        ("Peacock,Steve", "FULL", None, 200.00, 200.00, 125.00, 125.00, ""),
        ("Petchey,Ken", "ND", None, 200.00, 0.00, 0.00, 0.00, "Reminder sent 4th Jan"),
        ("Phillips,Andrew", "FULL", None, 200.00, 200.00, 125.00, 125.00, ""),
        ("Porter,John", "RESIGNED", None, 200.00, 200.00, 125.00, 125.00, "Arrears from last year, nothing owing now"),
        ("South,Ray", "DECEASED", None, 200.00, 0.00, 0.00, 0.00, "Write off of course"),
        ("Stock,Stephen", "FULL", None, 200.00, 200.00, 125.00, 125.00, ""),
        ("Stribling,Martyn", "ND", None, 200.00, 200.00, 0.00, 0.00, ""),
        ("Walden,Connor", "FULL", None, 200.00, 200.00, 125.00, 125.00, ""),
        ("Walden,Mark", "FULL", None, 200.00, 200.00, 125.00, 125.00, ""),
        ("Withey, Graham", "FULL", None, 200.00, 200.00, 125.00, 125.00, ""),
    ]

    member_type_ids = {
        row["code"]: row["id"]
        for row in db.execute("SELECT id, code FROM member_types").fetchall()
    }

    db.executemany(
        """
        INSERT INTO members (
            membership_number, full_name, member_type_id, email, phone, status, notes
        )
        VALUES (?, ?, ?, ?, ?, ?, ?)
        """,
        [
            (
                f"M{index:03d}",
                name,
                member_type_ids[member_code],
                None,
                None,
                (
                    "visitor" if member_code == "VISITOR"
                    else "excluded" if member_code == "EXCLUDE"
                    else "resigned" if member_code == "RESIGNED"
                    else "deceased" if member_code == "DECEASED"
                    else "active"
                ),
                notes,
            )
            for index, (name, member_code, _pp_subs, subs_due, subs_paid, dining_due, dining_paid, notes)
            in enumerate(member_rows, start=1)
        ],
    )

    db.executemany(
        """
        INSERT INTO dues (
            member_id, reporting_period_id, year,
            subscription_due, subscription_paid, dining_due, dining_paid, status, notes
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        [
            (
                index,
                1,
                2026,
                subs_due,
                subs_paid,
                dining_due,
                dining_paid,
                _dues_status(subs_due, subs_paid, dining_due, dining_paid, member_code),
                notes,
            )
            for index, (_name, member_code, _pp_subs, subs_due, subs_paid, dining_due, dining_paid, notes)
            in enumerate(member_rows, start=1)
        ],
    )

    db.executemany(
        """
        INSERT INTO subscription_charges (
            member_id, reporting_period_id, charge_type, description, amount, due_date, notes
        )
        VALUES (?, ?, ?, ?, ?, ?, ?)
        """,
        [
            (
                index,
                1,
                "annual",
                "Annual lodge subscription",
                subs_due,
                "2025-10-01",
                notes,
            )
            for index, (_name, member_code, _pp_subs, subs_due, _subs_paid, _dining_due, _dining_paid, notes)
            in enumerate(member_rows, start=1)
            if member_code != "VISITOR" and subs_due > 0
        ],
    )

    db.execute(
        """
        INSERT INTO events (title, event_date, meal_name, meal_price, booking_deadline, notes)
        VALUES (?, ?, ?, ?, ?, ?)
        """,
        (
            "April Lodge Dinner",
            "2026-04-21",
            "Three-course festive board",
            22.50,
            "2026-04-17",
            "Members can book meals and note dietary requirements.",
        ),
    )

    db.executemany(
        """
        INSERT INTO dining_charges (
            member_id, event_id, reporting_period_id, description, amount, status, notes
        )
        VALUES (?, ?, ?, ?, ?, ?, ?)
        """,
        [
            (
                index,
                1,
                1,
                "Annual dining balance",
                dining_due,
                "paid" if dining_due <= dining_paid else ("part-paid" if dining_paid > 0 else "due"),
                notes,
            )
            for index, (_name, member_code, _pp_subs, _subs_due, _subs_paid, dining_due, dining_paid, notes)
            in enumerate(member_rows, start=1)
            if member_code != "VISITOR" and dining_due > 0
        ],
    )

    db.executemany(
        """
        INSERT INTO bookings (event_id, member_id, seats, dietary_notes, status)
        VALUES (?, ?, ?, ?, ?)
        """,
        [
            (1, 2, 1, "", "confirmed"),
            (1, 10, 1, "", "confirmed"),
        ],
    )

    db.executemany(
        """
        INSERT INTO payments (
            member_id, reporting_period_id, payment_date, payment_method, reference,
            total_amount, subscription_amount, dining_amount, notes
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        [
            (
                index,
                1,
                "2025-09-10",
                "bank",
                f"IMPORT-{index:03d}",
                subs_paid + dining_paid,
                subs_paid,
                dining_paid,
                notes,
            )
            for index, (_name, member_code, _pp_subs, _subs_due, subs_paid, _dining_due, dining_paid, notes)
            in enumerate(member_rows, start=1)
            if member_code != "VISITOR" and (subs_paid + dining_paid) > 0
        ],
    )

    db.execute(
        """
        INSERT INTO messages (sender_name, sender_role, subject, body, status)
        VALUES (?, ?, ?, ?, ?)
        """,
        (
            "Secretary",
            "secretary",
            "Agenda reminder",
            "Please confirm the dues report is ready for the next committee meeting.",
            "open",
        ),
    )

    ensure_financial_tables(db)
    seed_ledger_categories(db)
    seed_virtual_accounts(db)
    seed_virtual_account_category_map(db)
    seed_virtual_account_balances(db, reporting_period_id=1)
    seed_bank_ledger(db, reporting_period_id=1)

    db.commit()


def seed_auth_users(db: DatabaseHandle) -> None:
    db.executemany(
        """
        INSERT INTO users (username, full_name, password_hash, role)
        VALUES (?, ?, ?, ?)
        ON CONFLICT(username) DO NOTHING
        """,
        [
            (username, full_name, generate_password_hash(password), role)
            for username, full_name, password, role in AUTH_USER_DEFINITIONS
        ],
    )


def init_app(app) -> None:
    @app.cli.command("init-db")
    def init_db_command() -> None:
        init_db()
        print("Initialized the database.")

    @app.cli.command("migrate-from-sqlite")
    def migrate_from_sqlite_command() -> None:
        sqlite_path = default_database_path()
        postgres_dsn = app.config["DATABASE"]
        if not _is_postgres_dsn(postgres_dsn):
            raise RuntimeError("The active database is not PostgreSQL.")
        totals = migrate_sqlite_database_to_postgres(sqlite_path, postgres_dsn)
        print(f"Migrated {totals['inserted_rows']} rows from SQLite to PostgreSQL.")

    @app.cli.command("backfill-bank-allocations")
    def backfill_bank_allocations_command() -> None:
        db = get_db()
        totals = backfill_bank_allocations_from_workbook(db)
        db.commit()
        print(
            f"Matched {totals['transactions_matched']} bank rows and wrote {totals['allocations_written']} allocations."
        )

    @app.cli.command("import-bank-statements")
    def import_bank_statements_command() -> None:
        db = get_db()
        reporting_period_id = 1
        totals = import_bank_statement_exports(db, reporting_period_id=reporting_period_id)
        if totals["files"] == 0:
            workbook_path = _find_existing_workbook()
            if workbook_path is not None:
                imported = import_bank_transactions_from_workbook(db, reporting_period_id, workbook_path)
                db.commit()
                print(f"Imported {imported} bank transactions from the workbook.")
                return
        db.commit()
        print(
            "Imported "
            f"{totals['inserted']} new and updated {totals['updated']} bank statement rows "
            f"from {totals['files']} CSV file(s)."
        )
