DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS cashbook_entries;
DROP TABLE IF EXISTS cash_settlements;
DROP TABLE IF EXISTS bank_transaction_allocations;
DROP TABLE IF EXISTS bank_transactions;
DROP TABLE IF EXISTS meetings;
DROP TABLE IF EXISTS app_settings;
DROP TABLE IF EXISTS ledger_categories;
DROP TABLE IF EXISTS dining_charges;
DROP TABLE IF EXISTS subscription_charges;
DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS dues;
DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS members;
DROP TABLE IF EXISTS member_types;
DROP TABLE IF EXISTS reporting_periods;

CREATE TABLE reporting_periods (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label TEXT NOT NULL UNIQUE,
    start_date TEXT NOT NULL,
    end_date TEXT NOT NULL,
    is_current INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);

CREATE TABLE member_types (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    description TEXT NOT NULL,
    subscription_rule TEXT NOT NULL,
    dining_rule TEXT NOT NULL,
    default_subscription_amount REAL NOT NULL DEFAULT 0,
    default_dining_amount REAL NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);

CREATE TABLE members (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    membership_number TEXT NOT NULL UNIQUE,
    full_name TEXT NOT NULL,
    member_type_id INTEGER,
    email TEXT,
    phone TEXT,
    status TEXT NOT NULL DEFAULT 'active',
    notes TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
    FOREIGN KEY (member_type_id) REFERENCES member_types (id)
);

CREATE TABLE dues (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id INTEGER NOT NULL,
    reporting_period_id INTEGER NOT NULL,
    year INTEGER NOT NULL,
    subscription_due REAL NOT NULL DEFAULT 0,
    subscription_paid REAL NOT NULL DEFAULT 0,
    dining_due REAL NOT NULL DEFAULT 0,
    dining_paid REAL NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'unpaid',
    notes TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
    FOREIGN KEY (member_id) REFERENCES members (id),
    FOREIGN KEY (reporting_period_id) REFERENCES reporting_periods (id)
);

CREATE TABLE events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    event_date TEXT NOT NULL,
    meal_name TEXT,
    meal_price REAL NOT NULL DEFAULT 0,
    booking_deadline TEXT,
    notes TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);

CREATE TABLE bookings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id INTEGER NOT NULL,
    member_id INTEGER NOT NULL,
    seats INTEGER NOT NULL DEFAULT 1,
    dietary_notes TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
    FOREIGN KEY (event_id) REFERENCES events (id),
    FOREIGN KEY (member_id) REFERENCES members (id)
);

CREATE TABLE messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_name TEXT NOT NULL,
    sender_role TEXT NOT NULL,
    subject TEXT NOT NULL,
    body TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'open',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);

CREATE TABLE subscription_charges (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id INTEGER NOT NULL,
    reporting_period_id INTEGER NOT NULL,
    charge_type TEXT NOT NULL,
    description TEXT NOT NULL,
    amount REAL NOT NULL DEFAULT 0,
    due_date TEXT,
    notes TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
    FOREIGN KEY (member_id) REFERENCES members (id),
    FOREIGN KEY (reporting_period_id) REFERENCES reporting_periods (id)
);

CREATE TABLE dining_charges (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id INTEGER NOT NULL,
    event_id INTEGER,
    reporting_period_id INTEGER NOT NULL,
    description TEXT NOT NULL,
    amount REAL NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'due',
    notes TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
    FOREIGN KEY (member_id) REFERENCES members (id),
    FOREIGN KEY (event_id) REFERENCES events (id),
    FOREIGN KEY (reporting_period_id) REFERENCES reporting_periods (id)
);

CREATE TABLE payments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id INTEGER NOT NULL,
    reporting_period_id INTEGER NOT NULL,
    payment_date TEXT NOT NULL,
    payment_method TEXT NOT NULL,
    reference TEXT,
    total_amount REAL NOT NULL DEFAULT 0,
    subscription_amount REAL NOT NULL DEFAULT 0,
    dining_amount REAL NOT NULL DEFAULT 0,
    notes TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
    FOREIGN KEY (member_id) REFERENCES members (id),
    FOREIGN KEY (reporting_period_id) REFERENCES reporting_periods (id)
);

CREATE TABLE ledger_categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    display_name TEXT NOT NULL,
    direction TEXT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);

CREATE TABLE app_settings (
    setting_key TEXT PRIMARY KEY,
    setting_value TEXT NOT NULL,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);

CREATE TABLE bank_transactions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporting_period_id INTEGER NOT NULL,
    transaction_date TEXT,
    details TEXT NOT NULL,
    transaction_type TEXT,
    money_in REAL NOT NULL DEFAULT 0,
    money_out REAL NOT NULL DEFAULT 0,
    running_balance REAL,
    is_opening_balance INTEGER NOT NULL DEFAULT 0,
    source_workbook TEXT,
    source_sheet TEXT,
    source_row_number INTEGER,
    notes TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
    FOREIGN KEY (reporting_period_id) REFERENCES reporting_periods (id),
    UNIQUE (source_workbook, source_sheet, source_row_number)
);

CREATE TABLE bank_transaction_allocations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_transaction_id INTEGER NOT NULL,
    ledger_category_id INTEGER NOT NULL,
    amount REAL NOT NULL,
    notes TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
    FOREIGN KEY (bank_transaction_id) REFERENCES bank_transactions (id) ON DELETE CASCADE,
    FOREIGN KEY (ledger_category_id) REFERENCES ledger_categories (id)
);

CREATE TABLE meetings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporting_period_id INTEGER NOT NULL,
    meeting_key TEXT NOT NULL UNIQUE,
    meeting_name TEXT NOT NULL,
    meeting_date TEXT,
    meeting_type TEXT NOT NULL DEFAULT 'Regular',
    sort_order INTEGER NOT NULL DEFAULT 0,
    notes TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
    FOREIGN KEY (reporting_period_id) REFERENCES reporting_periods (id)
);

CREATE TABLE cashbook_entries (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporting_period_id INTEGER NOT NULL,
    meeting_key TEXT NOT NULL CHECK (meeting_key IN ('SEPTEMBER', 'NOVEMBER', 'JANUARY', 'MARCH', 'MAY')),
    entry_type TEXT NOT NULL,
    entry_name TEXT NOT NULL,
    member_id INTEGER,
    ledger_category_id INTEGER,
    money_in REAL NOT NULL DEFAULT 0,
    money_out REAL NOT NULL DEFAULT 0,
    notes TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
    FOREIGN KEY (reporting_period_id) REFERENCES reporting_periods (id),
    FOREIGN KEY (member_id) REFERENCES members (id),
    FOREIGN KEY (ledger_category_id) REFERENCES ledger_categories (id)
);

CREATE TABLE cash_settlements (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporting_period_id INTEGER NOT NULL,
    meeting_key TEXT NOT NULL CHECK (meeting_key IN ('SEPTEMBER', 'NOVEMBER', 'JANUARY', 'MARCH', 'MAY')),
    settlement_date TEXT NOT NULL,
    net_amount REAL NOT NULL,
    bank_transaction_id INTEGER NOT NULL UNIQUE,
    notes TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
    FOREIGN KEY (reporting_period_id) REFERENCES reporting_periods (id),
    FOREIGN KEY (bank_transaction_id) REFERENCES bank_transactions (id) ON DELETE CASCADE
);

CREATE TABLE virtual_accounts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    display_name TEXT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);

CREATE TABLE virtual_account_balances (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporting_period_id INTEGER NOT NULL,
    virtual_account_id INTEGER NOT NULL,
    opening_balance REAL NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
    FOREIGN KEY (reporting_period_id) REFERENCES reporting_periods (id),
    FOREIGN KEY (virtual_account_id) REFERENCES virtual_accounts (id),
    UNIQUE (reporting_period_id, virtual_account_id)
);

CREATE TABLE virtual_account_category_map (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    virtual_account_id INTEGER NOT NULL,
    ledger_category_id INTEGER NOT NULL UNIQUE,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
    FOREIGN KEY (virtual_account_id) REFERENCES virtual_accounts (id),
    FOREIGN KEY (ledger_category_id) REFERENCES ledger_categories (id)
);

CREATE INDEX idx_members_member_type_id ON members (member_type_id);
CREATE INDEX idx_app_settings_updated_at ON app_settings (updated_at);
CREATE INDEX idx_dues_member_id ON dues (member_id);
CREATE INDEX idx_dues_reporting_period_id ON dues (reporting_period_id);
CREATE INDEX idx_subscription_charges_member_id ON subscription_charges (member_id);
CREATE INDEX idx_dining_charges_member_id ON dining_charges (member_id);
CREATE INDEX idx_payments_member_id ON payments (member_id);
CREATE INDEX idx_bank_transactions_date ON bank_transactions (transaction_date);
CREATE INDEX idx_bank_transactions_reporting_period_id ON bank_transactions (reporting_period_id);
CREATE INDEX idx_bank_transaction_allocations_transaction_id ON bank_transaction_allocations (bank_transaction_id);
CREATE INDEX idx_bank_transaction_allocations_category_id ON bank_transaction_allocations (ledger_category_id);
CREATE INDEX idx_cashbook_entries_meeting_key ON cashbook_entries (meeting_key);
CREATE INDEX idx_cash_settlements_meeting_key ON cash_settlements (meeting_key);
CREATE INDEX idx_virtual_account_balances_reporting_period_id ON virtual_account_balances (reporting_period_id);
CREATE INDEX idx_bookings_event_id ON bookings (event_id);
CREATE INDEX idx_messages_status ON messages (status);
